#ifndef ESM3_COMMON_H
#define ESM3_COMMON_H

#include <cstdint>
#include <string>

// From ScummVM's endianness.h but for little endian
#ifndef MKTAG
#define MKTAG(a0,a1,a2,a3) ((std::uint32_t)((a0) | ((a1) << 8) | ((a2) << 16) | ((a3) << 24)))
#endif

namespace ESM3
{
    // Based on http://www.uesp.net/wiki
    enum RecordTypes
    {
      //REC_AACT = MKTAG('A','A','C','T'), // Action
      //REC_ACHR = MKTAG('A','C','H','R'), // Actor Reference
        REC_ACTI = MKTAG('A','C','T','I'), // Activator
      //REC_ADDN = MKTAG('A','D','D','N'), // Addon Node
        REC_ALCH = MKTAG('A','L','C','H'), // Potion
      //REC_AMMO = MKTAG('A','M','M','O'), // Ammo
      //REC_ANIO = MKTAG('A','N','I','O'), // Animated Object
        REC_APPA = MKTAG('A','P','P','A'), // Apparatus
      //REC_ARMA = MKTAG('A','R','M','A'), // Armature (Model)
        REC_ARMO = MKTAG('A','R','M','O'), // Armor
      //REC_ARTO = MKTAG('A','R','T','O'), // Art Object
      //REC_ASPC = MKTAG('A','S','P','C'), // Acoustic Space
      //REC_ASTP = MKTAG('A','S','T','P'), // Association Type
      //REC_AVIF = MKTAG('A','V','I','F'), // Actor Values/Perk Tree Graphics
        REC_BSGN = MKTAG('B','S','G','N'), // Birthsign
        REC_BOOK = MKTAG('B','O','O','K'), // Book
      //REC_BPTD = MKTAG('B','P','T','D'), // Body Part Data
      //REC_CAMS = MKTAG('C','A','M','S'), // Camera Shot
        REC_CELL = MKTAG('C','E','L','L'), // Cell
        REC_CLAS = MKTAG('C','L','A','S'), // Class
      //REC_CLFM = MKTAG('C','L','F','M'), // Color
      //REC_CLMT = MKTAG('C','L','M','T'), // Climate
        REC_CLOT = MKTAG('C','L','O','T'), // Clothing
      //REC_COBJ = MKTAG('C','O','B','J'), // Constructible Object (recipes)
      //REC_COLL = MKTAG('C','O','L','L'), // Collision Layer
        REC_CONT = MKTAG('C','O','N','T'), // Container
      //REC_CPTH = MKTAG('C','P','T','H'), // Camera Path
        REC_CREA = MKTAG('C','R','E','A'), // Creature
      //REC_CSTY = MKTAG('C','S','T','Y'), // Combat Style
      //REC_DEBR = MKTAG('D','E','B','R'), // Debris
        REC_DIAL = MKTAG('D','I','A','L'), // Dialog Topic
      //REC_DLBR = MKTAG('D','L','B','R'), // Dialog Branch
      //REC_DLVW = MKTAG('D','L','V','W'), // Dialog View
      //REC_DOBJ = MKTAG('D','O','B','J'), // Default Object Manager
        REC_DOOR = MKTAG('D','O','O','R'), // Door
      //REC_DUAL = MKTAG('D','U','A','L'), // Dual Cast Data (possibly unused)
      //REC_ECZN = MKTAG('E','C','Z','N'), // Encounter Zone
      //REC_EFSH = MKTAG('E','F','S','H'), // Effect Shader
        REC_ENCH = MKTAG('E','N','C','H'), // Enchantment
      //REC_EQUP = MKTAG('E','Q','U','P'), // Equip Slot (flag-type values)
      //REC_EXPL = MKTAG('E','X','P','L'), // Explosion
      //REC_EYES = MKTAG('E','Y','E','S'), // Eyes
        REC_FACT = MKTAG('F','A','C','T'), // Faction
      //REC_FLOR = MKTAG('F','L','O','R'), // Flora
      //REC_FLST = MKTAG('F','L','S','T'), // Form List (non-levelled list)
      //REC_FSTP = MKTAG('F','S','T','P'), // Footstep
      //REC_FSTS = MKTAG('F','S','T','S'), // Footstep Set
      //REC_FURN = MKTAG('F','U','R','N'), // Furniture
        REC_GLOB = MKTAG('G','L','O','B'), // Global Variable
        REC_GMST = MKTAG('G','M','S','T'), // Game Setting
      //REC_GRAS = MKTAG('G','R','A','S'), // Grass
      //REC_GRUP = MKTAG('G','R','U','P'), // Form Group
      //REC_HAIR = MKTAG('H','A','I','R'), // Hair
      //REC_HAZD = MKTAG('H','A','Z','D'), // Hazard
      //REC_HDPT = MKTAG('H','D','P','T'), // Head Part
      //REC_IDLE = MKTAG('I','D','L','E'), // Idle Animation
      //REC_IDLM = MKTAG('I','D','L','M'), // Idle Marker
      //REC_IMAD = MKTAG('I','M','A','D'), // Image Space Modifier
      //REC_IMGS = MKTAG('I','M','G','S'), // Image Space
        REC_INFO = MKTAG('I','N','F','O'), // Dialog Topic Info
        REC_INGR = MKTAG('I','N','G','R'), // Ingredient
      //REC_IPCT = MKTAG('I','P','C','T'), // Impact Data
      //REC_IPDS = MKTAG('I','P','D','S'), // Impact Data Set
      //REC_KEYM = MKTAG('K','E','Y','M'), // Key
      //REC_KYWD = MKTAG('K','Y','W','D'), // Keyword
        REC_LAND = MKTAG('L','A','N','D'), // Land
      //REC_LCRT = MKTAG('L','C','R','T'), // Location Reference Type
      //REC_LCTN = MKTAG('L','C','T','N'), // Location
      //REC_LGTM = MKTAG('L','G','T','M'), // Lighting Template
        REC_LIGH = MKTAG('L','I','G','H'), // Light
        REC_LOCK = MKTAG('L','O','C','K'), // Lock
      //REC_LSCR = MKTAG('L','S','C','R'), // Load Screen
        REC_LTEX = MKTAG('L','T','E','X'), // Land Texture
      //REC_LVLC = MKTAG('L','V','L','C'), // Leveled Creature
      //REC_LVLI = MKTAG('L','V','L','I'), // Leveled Item
        REC_LEVC = MKTAG('L','E','V','C'), // Leveled Creature
        REC_LEVI = MKTAG('L','E','V','I'), // Leveled Item
      //REC_LVLN = MKTAG('L','V','L','N'), // Leveled Actor
      //REC_LVSP = MKTAG('L','V','S','P'), // Leveled Spell
      //REC_MATO = MKTAG('M','A','T','O'), // Material Object
      //REC_MATT = MKTAG('M','A','T','T'), // Material Type
      //REC_MESG = MKTAG('M','E','S','G'), // Message
        REC_MGEF = MKTAG('M','G','E','F'), // Magic Effect
        REC_MISC = MKTAG('M','I','S','C'), // Misc. Object
      //REC_MOVT = MKTAG('M','O','V','T'), // Movement Type
      //REC_MSTT = MKTAG('M','S','T','T'), // Movable Static
      //REC_MUSC = MKTAG('M','U','S','C'), // Music Type
      //REC_MUST = MKTAG('M','U','S','T'), // Music Track
      //REC_NAVI = MKTAG('N','A','V','I'), // Navigation (master data)
      //REC_NAVM = MKTAG('N','A','V','M'), // Nav Mesh
      //REC_NOTE = MKTAG('N','O','T','E'), // Note
        REC_NPC_ = MKTAG('N','P','C','_'), // Actor (NPC, Creature)
      //REC_OTFT = MKTAG('O','T','F','T'), // Outfit
      //REC_PACK = MKTAG('P','A','C','K'), // AI Package
      //REC_PERK = MKTAG('P','E','R','K'), // Perk
      //REC_PGRE = MKTAG('P','G','R','E'), // Placed grenade
      //REC_PHZD = MKTAG('P','H','Z','D'), // Placed hazard
        REC_PROB = MKTAG('P','R','O','B'), // Probe
      //REC_PROJ = MKTAG('P','R','O','J'), // Projectile
      //REC_QUST = MKTAG('Q','U','S','T'), // Quest
        REC_RACE = MKTAG('R','A','C','E'), // Race / Creature type
        REC_REPA = MKTAG('R','E','P','A'), // Repair
      //REC_REFR = MKTAG('R','E','F','R'), // Object Reference
        REC_REGN = MKTAG('R','E','G','N'), // Region (Audio/Weather)
      //REC_RELA = MKTAG('R','E','L','A'), // Relationship
      //REC_REVB = MKTAG('R','E','V','B'), // Reverb Parameters
      //REC_RFCT = MKTAG('R','F','C','T'), // Visual Effect
      //REC_SBSP = MKTAG('S','B','S','P'), // Subspace (TES4 only?)
      //REC_SCEN = MKTAG('S','C','E','N'), // Scene
        REC_SCPT = MKTAG('S','C','P','T'), // Script
      //REC_SCRL = MKTAG('S','C','R','L'), // Scroll
      //REC_SGST = MKTAG('S','G','S','T'), // Sigil Stone
      //REC_SHOU = MKTAG('S','H','O','U'), // Shout
      //REC_SLGM = MKTAG('S','L','G','M'), // Soul Gem
      //REC_SMBN = MKTAG('S','M','B','N'), // Story Manager Branch Node
      //REC_SMEN = MKTAG('S','M','E','N'), // Story Manager Event Node
      //REC_SMQN = MKTAG('S','M','Q','N'), // Story Manager Quest Node
      //REC_SNCT = MKTAG('S','N','C','T'), // Sound Category
      //REC_SNDR = MKTAG('S','N','D','R'), // Sound Reference
      //REC_SOPM = MKTAG('S','O','P','M'), // Sound Output Model
        REC_SOUN = MKTAG('S','O','U','N'), // Sound
        REC_SPEL = MKTAG('S','P','E','L'), // Spell
      //REC_SPGD = MKTAG('S','P','G','D'), // Shader Particle Geometry
        REC_STAT = MKTAG('S','T','A','T'), // Static
      //REC_TACT = MKTAG('T','A','C','T'), // Talking Activator
      //REC_TERM = MKTAG('T','E','R','M'), // Terminal
        REC_TES3 = MKTAG('T','E','S','3'), // Plugin info
      //REC_TES4 = MKTAG('T','E','S','4'), // Plugin info
      //REC_TREE = MKTAG('T','R','E','E'), // Tree
      //REC_TXST = MKTAG('T','X','S','T'), // Texture Set
      //REC_VTYP = MKTAG('V','T','Y','P'), // Voice Type
      //REC_WATR = MKTAG('W','A','T','R'), // Water Type
        REC_WEAP = MKTAG('W','E','A','P'), // Weapon
      //REC_WOOP = MKTAG('W','O','O','P'), // Word Of Power
      //REC_WRLD = MKTAG('W','R','L','D'), // World Space
      //REC_WTHR = MKTAG('W','T','H','R'), // Weather
      //REC_ACRE = MKTAG('A','C','R','E'), // Placed Creature (TES4 only?)
        REC_PGRD = MKTAG('P','G','R','D'), // Pathgrid
      //REC_ROAD = MKTAG('R','O','A','D'), // Road (TES4 only?)
      //REC_IMOD = MKTAG('I','M','O','D'), // Item Mod
      //REC_PWAT = MKTAG('P','W','A','T'), // Placeable Water
      //REC_SCOL = MKTAG('S','C','O','L'), // Static Collection
      //REC_CCRD = MKTAG('C','C','R','D'), // Caravan Card
      //REC_CMNY = MKTAG('C','M','N','Y'), // Caravan Money
      //REC_ALOC = MKTAG('A','L','O','C'), // Audio Location Controller
      //REC_MSET = MKTAG('M','S','E','T'), // Media Set
        REC_BODY = MKTAG('B','O','D','Y'), // Body Part
        REC_SNDG = MKTAG('S','N','D','G'), // Sound Generator
        REC_SSCR = MKTAG('S','S','C','R'), // Start Script
        REC_SKIL = MKTAG('S','K','I','L'), // Skill
        REC_SAVE = MKTAG('S','A','V','E'), // Saved Game
        REC_REFR = MKTAG('R','E','F','R'), // Player Save Game?
        REC_PCDT = MKTAG('P','C','D','T'), // Player Data
        REC_CNTC = MKTAG('C','N','T','C'), // Container changes
        REC_CREC = MKTAG('C','R','E','C'), // Creature changes
        REC_NPCC = MKTAG('N','P','C','C'), // NPC changes
        REC_QUES = MKTAG('Q','U','E','S'), // Quest changes
        REC_JOUR = MKTAG('J','O','U','R'), // Journal changes
        REC_PROJ = MKTAG('P','R','O','J'),
        REC_KLST = MKTAG('K','L','S','T'),
        REC_SPLM = MKTAG('S','P','L','M'),
        REC_GMAP = MKTAG('G','M','A','P'),
        REC_CSTA = MKTAG('C','S','T','A'),
        REC_STLN = MKTAG('S','T','L','N'),
        REC_FILT = MKTAG('F','I','L','T'), // Filter
        REC_DBGP = MKTAG('D','B','G','P')  // Debug Profile
    };

    enum SubRecordTypes
    {
        SUB_HEDR = MKTAG('H','E','D','R'),
        SUB_CNAM = MKTAG('C','N','A','M'),
        SUB_FORM = MKTAG('F','O','R','M'),
        SUB_MAST = MKTAG('M','A','S','T'),
        SUB_DATA = MKTAG('D','A','T','A'),
        SUB_GMDT = MKTAG('G','M','D','T'), // TES3

        SUB_PLNA = MKTAG('P','L','N','A'),
        SUB_PLLE = MKTAG('P','L','L','E'),
        SUB_PLCL = MKTAG('P','L','C','L'),
        SUB_PLCN = MKTAG('P','L','C','N'),
        SUB_PLCE = MKTAG('P','L','C','E'),
        SUB_TSTM = MKTAG('T','S','T','M'),
        SUB_TIME = MKTAG('T','I','M','E'),
        SUB_DEPE = MKTAG('D','E','P','E'),
        SUB_SCRN = MKTAG('S','C','R','N'),
        SUB_WIDX = MKTAG('W','I','D','X'),
        SUB_XIDX = MKTAG('X','I','D','X'),
        SUB_XHLT = MKTAG('X','H','L','T'),
        SUB_ACTN = MKTAG('A','C','T','N'),
        SUB_STPR = MKTAG('S','T','P','R'),
        SUB_MNAM = MKTAG('M','N','A','M'),
        SUB_ACDT = MKTAG('A','C','D','T'),
        SUB_ACSC = MKTAG('A','C','S','C'),
        SUB_ACSL = MKTAG('A','C','S','L'),
        SUB_CSTN = MKTAG('C','S','T','N'),
        SUB_LSTN = MKTAG('L','S','T','N'),
        SUB_CSHN = MKTAG('C','S','H','N'),
        SUB_LSHN = MKTAG('L','S','H','N'),
        SUB_TGTN = MKTAG('T','G','T','N'),
        SUB_FGTN = MKTAG('F','G','T','N'),
        SUB_PWPC = MKTAG('P','W','P','C'),
        SUB_PWPS = MKTAG('P','W','P','S'),
        SUB_ND3D = MKTAG('N','D','3','D'),
        SUB_XNAM = MKTAG('X','N','A','M'),
        SUB_YNAM = MKTAG('Y','N','A','M'),
        SUB_APUD = MKTAG('A','P','U','D'),
        SUB_CHRD = MKTAG('C','H','R','D'),
        SUB_CRED = MKTAG('C','R','E','D'),
        SUB_ANIS = MKTAG('A','N','I','S'),
        SUB_WERE = MKTAG('W','E','R','E'),
        SUB_LKEP = MKTAG('L','K','E','P'), // last known exterior position
        SUB_MARK = MKTAG('M','A','R','K'), // marked position
        SUB_AMOV = MKTAG('A','M','O','V'),
        SUB_SIGN = MKTAG('S','I','G','N'),
        SUB_CURD = MKTAG('C','U','R','D'),
        SUB_PAYD = MKTAG('P','A','Y','D'),
        SUB_BOUN = MKTAG('B','O','U','N'),
        SUB_PREV = MKTAG('P','R','E','V'),
        SUB_SLCS = MKTAG('S','L','C','S'),
        SUB_SLSD = MKTAG('S','L','S','D'),
        SUB_SLLD = MKTAG('S','L','L','D'),
        SUB_SLFD = MKTAG('S','L','F','D'),
        SUB_MPCD = MKTAG('M','P','C','D'),
        SUB_LVCR = MKTAG('L','V','C','R'),
        SUB_IOBJ = MKTAG('I','O','B','J'),
        SUB_SLOT = MKTAG('S','L','O','T'),
        SUB_ICNT = MKTAG('I','C','N','T'),
        SUB_LEVM = MKTAG('L','E','V','M'),
        SUB_LGRP = MKTAG('L','G','R','P'),
        SUB_MAGI = MKTAG('M','A','G','I'),
        SUB_EQUI = MKTAG('E','Q','U','I'),
        SUB_EQIP = MKTAG('E','Q','I','P'),
        SUB_SELE = MKTAG('S','E','L','E'),
        SUB_MULT = MKTAG('M','U','L','T'),
        SUB_RAND = MKTAG('R','A','N','D'),
        SUB_COUN = MKTAG('C','O','U','N'),
        SUB_MAPH = MKTAG('M','A','P','H'),
        SUB_MAPD = MKTAG('M','A','P','D'),
        SUB_MPNT = MKTAG('M','P','N','T'),
        SUB_ID__ = MKTAG('I','D','_','_'), // actors, quick keys and activespell
        SUB_CFLG = MKTAG('C','F','L','G'), // control state
        SUB_BNDS = MKTAG('B','N','D','S'), // global map
        SUB_MRK_ = MKTAG('M','R','K','_'), // global map
        SUB_POSX = MKTAG('P','O','S','X'), // custom marker
        SUB_POSY = MKTAG('P','O','S','Y'), // custom marker
        SUB_NOTE = MKTAG('N','O','T','E'), // custom marker
        SUB_KEY_ = MKTAG('K','E','Y','_'), // quick keys
        SUB_TYPE = MKTAG('T','Y','P','E'), // quick keys
        SUB_TARG = MKTAG('T','A','R','G'), // global script
        SUB_RUN_ = MKTAG('R','U','N','_'), // global script
        SUB_TELE = MKTAG('T','E','L','E'), // teleport enabled
        SUB_LEVT = MKTAG('L','E','V','T'), // levitation enabled
        SUB_FIRS = MKTAG('F','I','R','S'), // first person cam
        SUB_CREG = MKTAG('C','R','E','G'), // weather state
        SUB_TMPS = MKTAG('T','M','P','S'), // weather state
        SUB_FAST = MKTAG('F','A','S','T'), // weather state
        SUB_WUPD = MKTAG('W','U','P','D'), // weather state
        SUB_TRFC = MKTAG('T','R','F','C'), // weather state
        SUB_CWTH = MKTAG('C','W','T','H'), // weather state
        SUB_NWTH = MKTAG('N','W','T','H'), // weather state
        SUB_QWTH = MKTAG('Q','W','T','H'), // weather state
        SUB_RGNW = MKTAG('R','G','N','W'), // weather state
        SUB_RGNC = MKTAG('R','G','N','C'), // weather state
        SUB_LUAS = MKTAG('L','U','A','S'), // lua
        SUB_LUAT = MKTAG('L','U','A','T'), // lua
        SUB_LUAC = MKTAG('L','U','A','C'), // lua
        SUB_LUAD = MKTAG('L','U','A','D'), // lua
        SUB_LUAE = MKTAG('L','U','A','E'), // lua
        SUB_CAST = MKTAG('C','A','S','T'), // active spells
        SUB_DISP = MKTAG('D','I','S','P'), // active spells
        SUB_MGEF = MKTAG('M','G','E','F'), // active spells
        SUB_ARG_ = MKTAG('A','R','G','_'), // active spells
        SUB_MAGN = MKTAG('M','A','G','N'), // active spells
        SUB_DURA = MKTAG('D','U','R','A'), // active spells
        SUB_LEFT = MKTAG('L','E','F','T'), // active spells
        SUB_EIND = MKTAG('E','I','N','D'), // active spells
        SUB_HLOC = MKTAG('H','L','O','C'), // object state
        SUB_ENAB = MKTAG('E','N','A','B'), // object state
        SUB_HCUS = MKTAG('H','C','U','S'), // object state
        SUB_POS_ = MKTAG('P','O','S','_'), // object state
        SUB_LROT = MKTAG('L','R','O','T'), // object state
        SUB_LTIM = MKTAG('L','T','I','M'), // object state
        SUB_ABST = MKTAG('A','B','S','T'), // animation state
        SUB_GOLD = MKTAG('G','O','L','D'), // creature stats
        SUB_AFLG = MKTAG('A','F','L','G'), // creature stats
        SUB_DEAD = MKTAG('D','E','A','D'), // creature stats
        SUB_DFNT = MKTAG('D','F','N','T'), // creature stats
        SUB_DIED = MKTAG('D','I','E','D'), // creature stats
        SUB_MURD = MKTAG('M','U','R','D'), // creature stats
        SUB_FRHT = MKTAG('F','R','H','T'), // creature stats
        SUB_TALK = MKTAG('T','A','L','K'), // creature stats
        SUB_ALRM = MKTAG('A','L','R','M'), // creature stats
        SUB_ATKD = MKTAG('A','T','K','D'), // creature stats
        SUB_HOST = MKTAG('H','O','S','T'), // creature stats
        SUB_ATCK = MKTAG('A','T','C','K'), // creature stats
        SUB_KNCK = MKTAG('K','N','C','K'), // creature stats
        SUB_KNC1 = MKTAG('K','N','C','1'), // creature stats
        SUB_KNCO = MKTAG('K','N','C','O'), // creature stats
        SUB_HITR = MKTAG('H','I','T','R'), // creature stats
        SUB_BLCK = MKTAG('B','L','C','K'), // creature stats
        SUB_MOVE = MKTAG('M','O','V','E'), // creature stats
        SUB_ASTR = MKTAG('A','S','T','R'), // creature stats
        SUB_FALL = MKTAG('F','A','L','L'), // creature stats
        SUB_LHIT = MKTAG('L','H','I','T'), // creature stats
        SUB_LHAT = MKTAG('L','H','A','T'), // creature stats
        SUB_CALC = MKTAG('C','A','L','C'), // creature stats
        SUB_DRAW = MKTAG('D','R','A','W'), // creature stats
        SUB_LEVL = MKTAG('L','E','V','L'), // creature stats
        SUB_ACID = MKTAG('A','C','I','D'), // creature stats
        SUB_WORS = MKTAG('W','O','R','S'), // creature stats
        SUB_DANM = MKTAG('D','A','N','M'), // creature stats
        SUB_DTIM = MKTAG('D','T','I','M'), // creature stats
        SUB_SPEL = MKTAG('S','P','E','L'), // creature stats
        SUB_SUMM = MKTAG('S','U','M','M'), // creature stats
        SUB_SOUR = MKTAG('S','O','U','R'), // creature stats
        SUB_GRAV = MKTAG('G','R','A','V'), // creature stats
        SUB_CORP = MKTAG('C','O','R','P'), // creature stats
        SUB_AISE = MKTAG('A','I','S','E'), // creature stats
        SUB_AIPK = MKTAG('A','I','P','K'), // ai sequence
        SUB_ALWY = MKTAG('A','L','W','Y'), // ai sequence
        SUB_CMND = MKTAG('C','M','N','D'), // ai sequence
        SUB_LAST = MKTAG('L','A','S','T'), // ai sequence
        SUB_ACTV = MKTAG('A','C','T','V'), // ai sequence
        SUB_HIDD = MKTAG('H','I','D','D'), // ai sequence
        SUB_TAID = MKTAG('T','A','I','D'), // ai sequence
        SUB_CELL = MKTAG('C','E','L','L'), // ai sequence
        SUB_EFID = MKTAG('E','F','I','D'), // magic effects
        SUB_PERM = MKTAG('P','E','R','M'), // spell state
        SUB_SLCT = MKTAG('S','L','C','T'), // spell state
        SUB_USED = MKTAG('U','S','E','D'), // spell state
        SUB_PURG = MKTAG('P','U','R','G'), // spell state
        SUB_BASE = MKTAG('B','A','S','E'), // spell state
        SUB_OBJE = MKTAG('O','B','J','E'), // cell references
        SUB_TOPI = MKTAG('T','O','P','I'),
        SUB_FACT = MKTAG('F','A','C','T'),
        SUB_REAC = MKTAG('R','E','A','C'),
        SUB_REA2 = MKTAG('R','E','A','2'),
        SUB_QSTA = MKTAG('Q','S','T','A'), // quest state
        SUB_QFIN = MKTAG('Q','F','I','N'), // quest state
        SUB_YETO = MKTAG('Y','E','T','O'), // quest state
        SUB_STBA = MKTAG('S','T','B','A'), // stat state
        SUB_STMO = MKTAG('S','T','M','O'), // stat state
        SUB_STCU = MKTAG('S','T','C','U'), // stat state
        SUB_STDA = MKTAG('S','T','D','A'), // stat state
        SUB_STDF = MKTAG('S','T','D','F'), // stat state
        SUB_FAEX = MKTAG('F','A','E','X'), // npc stats
        SUB_FARA = MKTAG('F','A','R','A'), // npc stats
        SUB_FARE = MKTAG('F','A','R','E'), // npc stats
        SUB_HWAT = MKTAG('H','W','A','T'), // npc stats
        SUB_WOLF = MKTAG('W','O','L','F'), // npc stats
        SUB_REPU = MKTAG('R','E','P','U'), // npc stats
        SUB_WKIL = MKTAG('W','K','I','L'), // npc stats
        SUB_PROF = MKTAG('P','R','O','F'), // npc stats
        SUB_LPRO = MKTAG('L','P','R','O'), // npc stats
        SUB_INCR = MKTAG('I','N','C','R'), // npc stats
        SUB_SPEC = MKTAG('S','P','E','C'), // npc stats
        SUB_DRTI = MKTAG('D','R','T','I'), // npc stats
        SUB_DRLH = MKTAG('D','R','L','H'), // npc stats
        SUB_LVLH = MKTAG('L','V','L','H'), // npc stats
        SUB_CRID = MKTAG('C','R','I','D'), // npc stats
        SUB_JETY = MKTAG('J','E','T','Y'), // journal state
        SUB_YEIN = MKTAG('Y','E','I','N'), // journal state
        SUB_JEDA = MKTAG('J','E','D','A'), // journal state
        SUB_JEMO = MKTAG('J','E','M','O'), // journal state
        SUB_JEDM = MKTAG('J','E','D','M'), // journal state
        SUB_ACT_ = MKTAG('A','C','T','_'), // journal state
        SUB_SPAW = MKTAG('S','P','A','W'), // creature levlist state
        SUB_RESP = MKTAG('R','E','S','P'), // creature levlist state
        SUB_ANIM = MKTAG('A','N','I','M'), // door state
        SUB_ANGL = MKTAG('A','N','G','L'), // fog state
        SUB_FTEX = MKTAG('F','T','E','X'), // fog state
        SUB_WLVL = MKTAG('W','L','V','L'), // cell state
        SUB_HFOW = MKTAG('H','F','O','W'), // cell state
        SUB_VEC3 = MKTAG('V','E','C','3'), // projectile state
        SUB_QUAT = MKTAG('Q','U','A','T'), // projectile state
        SUB_ACTO = MKTAG('A','C','T','O'), // projectile state
        SUB_SRCN = MKTAG('S','R','C','N'), // projectile state
        SUB_SPED = MKTAG('S','P','E','D'), // projectile state
        SUB_STCK = MKTAG('S','T','C','K'), // projectile state
        SUB_SOUN = MKTAG('S','O','U','N'), // projectile state
        SUB_VEL_ = MKTAG('V','E','L','_'), // projectile state
        SUB_BOW_ = MKTAG('B','O','W','_'), // projectile state
        SUB_STR_ = MKTAG('S','T','R','_'), // projectile state

        SUB_AIDT = MKTAG('A','I','D','T'),
        SUB_AI_A = MKTAG('A','I','_','A'),
        SUB_AI_E = MKTAG('A','I','_','E'),
        SUB_AI_F = MKTAG('A','I','_','F'),
        SUB_AI_T = MKTAG('A','I','_','T'),
        SUB_AI_W = MKTAG('A','I','_','W'),
        SUB_AMBI = MKTAG('A','M','B','I'),
        SUB_ANAM = MKTAG('A','N','A','M'),
        SUB_ASND = MKTAG('A','S','N','D'),
        SUB_AVFX = MKTAG('A','V','F','X'),
        SUB_BNAM = MKTAG('B','N','A','M'),
        SUB_BSND = MKTAG('B','S','N','D'),
        SUB_BVFX = MKTAG('B','V','F','X'),
        SUB_CIDX = MKTAG('C','I','D','X'),
        SUB_CNDT = MKTAG('C','N','D','T'),
        SUB_CSND = MKTAG('C','S','N','D'),
        SUB_CTDT = MKTAG('C','T','D','T'),
        SUB_CVFX = MKTAG('C','V','F','X'),
        SUB_DELE = MKTAG('D','E','L','E'),
        SUB_DESC = MKTAG('D','E','S','C'),
        SUB_DNAM = MKTAG('D','N','A','M'),
        SUB_DODT = MKTAG('D','O','D','T'),
        SUB_ENAM = MKTAG('E','N','A','M'),
        SUB_FILT = MKTAG('F','I','L','T'),
        SUB_FLAG = MKTAG('F','L','A','G'),
        SUB_FLTV = MKTAG('F','L','T','V'),
        SUB_FNAM = MKTAG('F','N','A','M'),
        SUB_HSND = MKTAG('H','S','N','D'),
        SUB_HVFX = MKTAG('H','V','F','X'),
        SUB_INAM = MKTAG('I','N','A','M'),
        SUB_INDX = MKTAG('I','N','D','X'),
        SUB_INTV = MKTAG('I','N','T','V'),
        SUB_ITEX = MKTAG('I','T','E','X'),
        SUB_KNAM = MKTAG('K','N','A','M'),
        SUB_LNAM = MKTAG('L','N','A','M'),
        SUB_LOCA = MKTAG('L','O','C','A'),
        SUB_MODL = MKTAG('M','O','D','L'),
        SUB_NAM0 = MKTAG('N','A','M','0'),
        SUB_NAM1 = MKTAG('N','A','M','1'),
        SUB_NAM2 = MKTAG('N','A','M','2'),
        SUB_NAM3 = MKTAG('N','A','M','3'),
        SUB_NAM5 = MKTAG('N','A','M','5'),
        SUB_NAM8 = MKTAG('N','A','M','8'),
        SUB_NAM9 = MKTAG('N','A','M','9'),
        SUB_NAME = MKTAG('N','A','M','E'),
        SUB_NNAM = MKTAG('N','N','A','M'),
        SUB_ZNAM = MKTAG('Z','N','A','M'),
        SUB_NPCO = MKTAG('N','P','C','O'),
        SUB_NPCS = MKTAG('N','P','C','S'),
        SUB_NPDT = MKTAG('N','P','D','T'),
        SUB_ONAM = MKTAG('O','N','A','M'),
        SUB_PGRC = MKTAG('P','G','R','C'),
        SUB_PGRP = MKTAG('P','G','R','P'),
        SUB_PNAM = MKTAG('P','N','A','M'),
        SUB_PTEX = MKTAG('P','T','E','X'),
        SUB_QSTF = MKTAG('Q','S','T','F'),
        SUB_QSTN = MKTAG('Q','S','T','N'),
        SUB_QSTR = MKTAG('Q','S','T','R'),
        SUB_RGNN = MKTAG('R','G','N','N'),
        SUB_RNAM = MKTAG('R','N','A','M'),
        SUB_SCHD = MKTAG('S','C','H','D'),
        SUB_SCRD = MKTAG('S','C','R','D'),
        SUB_SCRI = MKTAG('S','C','R','I'),
        SUB_SCRP = MKTAG('S','C','R','P'),
        SUB_SCRS = MKTAG('S','C','R','S'),
        SUB_SCTX = MKTAG('S','C','T','X'),
        SUB_SCVR = MKTAG('S','C','V','R'),
        SUB_SKDT = MKTAG('S','K','D','T'),
        SUB_SNAM = MKTAG('S','N','A','M'),
        SUB_SPAC = MKTAG('S','P','A','C'),
        SUB_STRV = MKTAG('S','T','R','V'),
        SUB_STTV = MKTAG('S','T','T','V'),
        SUB_TEXT = MKTAG('T','E','X','T'),
        SUB_TNAM = MKTAG('T','N','A','M'),
        SUB_UNAM = MKTAG('U','N','A','M'),
        SUB_VCLR = MKTAG('V','C','L','R'),
        SUB_VHGT = MKTAG('V','H','G','T'),
        SUB_VNML = MKTAG('V','N','M','L'),
        SUB_VTEX = MKTAG('V','T','E','X'),
        SUB_WHGT = MKTAG('W','H','G','T'),
        SUB_WNAM = MKTAG('W','N','A','M'),
        SUB_XCHG = MKTAG('X','C','H','G'),
        SUB_XSCL = MKTAG('X','S','C','L'),
        SUB_XSOL = MKTAG('X','S','O','L'),

        SUB_WEAT = MKTAG('W','E','A','T'), // Region
        SUB_SCDT = MKTAG('S','C','D','T'), // Script
        SUB_MEDT = MKTAG('M','E','D','T'), // Magic Effect
        SUB_RADT = MKTAG('R','A','D','T'), // Race
        SUB_BYDT = MKTAG('B','Y','D','T'), // Body
        SUB_CLDT = MKTAG('C','L','D','T'), // Class
        SUB_ALDT = MKTAG('A','L','D','T'), // Potion
        SUB_AADT = MKTAG('A','A','D','T'), // Apparatus
        SUB_AODT = MKTAG('A','O','D','T'), // Armor
        SUB_BKDT = MKTAG('B','K','D','T'), // Book
        SUB_IRDT = MKTAG('I','R','D','T'), // Ingredient
        SUB_LHDT = MKTAG('L','H','D','T'), // Light
        SUB_LKDT = MKTAG('L','K','D','T'), // Lock
        SUB_PBDT = MKTAG('P','B','D','T'), // Probe
        SUB_RIDT = MKTAG('R','I','D','T'), // Repair
        SUB_WPDT = MKTAG('W','P','D','T'), // Weapon
        SUB_MCDT = MKTAG('M','C','D','T'), // Misc
        SUB_SPDT = MKTAG('S','P','D','T'), // Spell
        SUB_FADT = MKTAG('F','A','D','T'), // Faction
        SUB_ENDT = MKTAG('E','N','D','T'), // Enchant

        SUB_MVRF = MKTAG('M','V','R','F'), // Moved Reference
        SUB_FRMR = MKTAG('F','R','M','R')  // Form Reference
    };

    enum RecordFlag
    {
        Rec_Deleted    = 0x00000020, // Deleted
        Rec_Persistent = 0x00000400, // Persistent reference
        Rec_Disabled   = 0x00000800, // Initially disabled
        Rec_Danger     = 0x00002000  // Blocked
    };

#pragma pack(push, 1)
    struct RecordHeader
    {
        std::uint32_t typeId;
        std::uint32_t dataSize;
        std::uint32_t unknown;
        std::uint32_t flags;
    };

    struct SubRecordHeader
    {
        std::uint32_t typeId;
        std::uint32_t dataSize;
    };
#pragma pack(pop)
}

#endif // ESM3_COMMON_H
